When we tried to locally close the issue, it did not actually close the issue on the project. It just showed that there was a commit that referenced this issue.
We had to actually create a pull request in order to merge the commit upstream. Once we merged it, then the issue closed.
